spring:
  application:
    name: open-api


logging:
  level:
    root: warn
    com.king: info
    org.springframework: error
  file:
    name: file
    path: /tmp/logs/open-api.log
  pattern:
    level: %5p
